### ISSUE TITLE
10s connection timeout may be too short

### ISSUE THREAD

**Issue by jmtcsngr** [jeromekelleher/ga4gh-streaming-tester#16]
When requesting from a relatively slow (mine) server, I'm getting time out in https connections.
```
$ python --version
Python 2.7.10
$ pip list
certifi (2017.7.27.1)
chardet (3.0.4)
htsget (0.2.0)
humanize (0.5.1)
idna (2.6)
pip (7.1.2)
pysam (0.11.2.2)
requests (2.18.4)
setuptools (18.2)
six (1.11.0)
urllib3 (1.22)
wheel (0.24.0)
```
Calls are generated through the tester, but the exception stack trace points to htsget io file
```
2017-09-19 12:38:00,809 htsget-api: request (name='chr22_KI270733v1_random', md5='None', start=179702, end=179707)
2017-09-19 12:38:00,810 handle_ticket_request(url=https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/ga4gh/sample/ENCFF284YOU_GRCH38?start=179702&format=BAM&end=179707&referenceName=chr22_KI270733v1_random)
2017-09-19 12:38:00,813 Starting new HTTPS connection (1): htsget.wtsi-npg-test.co.uk
2017-09-19 12:38:00,928 https://htsget.wtsi-npg-test.co.uk:9090 "GET /npg_ranger/ga4gh/sample/ENCFF284YOU_GRCH38?start=179702&format=BAM&end=179707&referenceName=chr22_KI270733v1_random HTTP/1.1" 200 191
2017-09-19 12:38:00,933 handle_http_url(url=https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707, headers=)
2017-09-19 12:38:00,936 Starting new HTTPS connection (1): htsget.wtsi-npg-test.co.uk
2017-09-19 12:38:01,696 https://htsget.wtsi-npg-test.co.uk:9090 "GET /npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707 HTTP/1.1" 200 None
2017-09-19 12:38:11,710 Error: 'HTTPSConnectionPool(host='htsget.wtsi-npg-test.co.uk', port=9090): Read timed out.' occured; sleeping 5s before retrying (attempt=1)
2017-09-19 12:38:16,716 handle_http_url(url=https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707, headers=)
2017-09-19 12:38:16,722 Starting new HTTPS connection (1): htsget.wtsi-npg-test.co.uk
2017-09-19 12:38:17,558 https://htsget.wtsi-npg-test.co.uk:9090 "GET /npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707 HTTP/1.1" 200 None
2017-09-19 12:38:27,573 Error: 'HTTPSConnectionPool(host='htsget.wtsi-npg-test.co.uk', port=9090): Read timed out.' occured; sleeping 5s before retrying (attempt=2)
2017-09-19 12:38:32,579 handle_http_url(url=https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707, headers=)
2017-09-19 12:38:32,582 Starting new HTTPS connection (1): htsget.wtsi-npg-test.co.uk
2017-09-19 12:38:33,868 https://htsget.wtsi-npg-test.co.uk:9090 "GET /npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707 HTTP/1.1" 200 None
2017-09-19 12:38:43,882 Error: 'HTTPSConnectionPool(host='htsget.wtsi-npg-test.co.uk', port=9090): Read timed out.' occured; sleeping 5s before retrying (attempt=3)
2017-09-19 12:38:48,888 handle_http_url(url=https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707, headers=)
2017-09-19 12:38:48,891 Starting new HTTPS connection (1): htsget.wtsi-npg-test.co.uk
2017-09-19 12:38:49,594 https://htsget.wtsi-npg-test.co.uk:9090 "GET /npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707 HTTP/1.1" 200 None
2017-09-19 12:38:59,608 Error: 'HTTPSConnectionPool(host='htsget.wtsi-npg-test.co.uk', port=9090): Read timed out.' occured; sleeping 5s before retrying (attempt=4)
2017-09-19 12:39:04,614 handle_http_url(url=https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707, headers=)
2017-09-19 12:39:04,618 Starting new HTTPS connection (1): htsget.wtsi-npg-test.co.uk
2017-09-19 12:39:05,308 https://htsget.wtsi-npg-test.co.uk:9090 "GET /npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707 HTTP/1.1" 200 None
2017-09-19 12:39:15,322 Error: 'HTTPSConnectionPool(host='htsget.wtsi-npg-test.co.uk', port=9090): Read timed out.' occured; sleeping 5s before retrying (attempt=5)
2017-09-19 12:39:20,328 handle_http_url(url=https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707, headers=)
2017-09-19 12:39:20,333 Starting new HTTPS connection (1): htsget.wtsi-npg-test.co.uk
2017-09-19 12:39:21,171 https://htsget.wtsi-npg-test.co.uk:9090 "GET /npg_ranger/sample?accession=ENCFF284YOU_GRCH38&format=BAM&region=chr22_KI270733v1_random%3A179703-179707 HTTP/1.1" 200 None
Traceback (most recent call last):
  File "tester.py", line 766, in <module>
    tester.run_end_reads()
  File "tester.py", line 672, in run_end_reads
    reference_name=contig.reference_name, start=start, end=end)
  File "tester.py", line 552, in verify_query
    start=start, end=end, data_format=self.data_format)
  File "tester.py", line 67, in htsget_api
    start=start, end=end, data_format=data_format)
  File "/nfs/users/nfs_j/jmtc/projects/streaming_tester/venv/lib/python2.7/site-packages/htsget/io.py", line 70, in get
    manager.run()
  File "/nfs/users/nfs_j/jmtc/projects/streaming_tester/venv/lib/python2.7/site-packages/htsget/protocol.py", line 146, in run
    self.__retry(self._handle_http_url, urlunparse(url), headers)
  File "/nfs/users/nfs_j/jmtc/projects/streaming_tester/venv/lib/python2.7/site-packages/htsget/protocol.py", line 122, in __retry
    raise re
htsget.exceptions.RetryableIOError: HTTPSConnectionPool(host='htsget.wtsi-npg-test.co.uk', port=9090): Read timed out.
++ set -e
```
can replicate directly with the library
```
>>> import htsget
>>> url = "https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/ga4gh/sample/ENCFF284YOU_GRCH38"
>>> with open("output.bam", "wb") as output:
...     htsget.get(url, output, reference_name="chr22_KI270733v1_random", start=179702, end=179707)
... 
WARNING:root:Error: 'HTTPSConnectionPool(host='htsget.wtsi-npg-test.co.uk', port=9090): Read timed out.' occured; sleeping 5s before retrying (attempt=1)
^CTraceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/nfs/users/nfs_j/jmtc/projects/streaming_tester/venv/lib/python2.7/site-packages/htsget/io.py", line 70, in get
    manager.run()
  File "/nfs/users/nfs_j/jmtc/projects/streaming_tester/venv/lib/python2.7/site-packages/htsget/protocol.py", line 146, in run
    self.__retry(self._handle_http_url, urlunparse(url), headers)
  File "/nfs/users/nfs_j/jmtc/projects/streaming_tester/venv/lib/python2.7/site-packages/htsget/protocol.py", line 120, in __retry
    time.sleep(sleep_time)
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> quit()
```
passing a longer time out fixes things
```
python
Python 2.7.10 (default, Sep  3 2015, 11:05:41) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import htsget
>>> url = "https://htsget.wtsi-npg-test.co.uk:9090/npg_ranger/ga4gh/sample/ENCFF284YOU_GRCH38"
>>> with open("output.bam", "wb") as output:
...     htsget.get(url, output, reference_name="chr22_KI270733v1_random", start=179702, end=179707, timeout=100)
... 
>>> quit()
$ samtools flagstat output.bam 
16200 + 1398 in total (QC-passed reads + QC-failed reads)
16200 + 1396 secondary
0 + 0 supplementary
0 + 0 duplicates
16200 + 1398 mapped (100.00% : 100.00%)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
Will you consider increasing time out to say 120s? Maybe worth considering increasing the default time out altogether.

**Comment by jeromekelleher** [comment]
> Will you consider increasing time out to say 120s? Maybe worth considering increasing the default time out altogether.

Yes, definitely. There's no particularly reason for 10s, I was just plucking numbers from thin air. I'm happy to adopt any (non-infinite) timeout you suggest.

**Comment by jmtcsngr** [comment]
Great, created #17 to address it in this side of the code. If things look good maybe can be pushed up to be part of htsget.io

**Comment by jeromekelleher** [comment]
Closing this, and moving the long-term discussion to https://github.com/jeromekelleher/htsget/issues/22.
